apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        # IMPORTANT: Change this to your actual Docker Hub username!
        # Change the v1 to v3 here: as we are rolling out v3 of our app with configmaps and secrets
        image: neyo55/fastapi-app:a00bf57
        ports:
        - containerPort: 8000
        env:
        - name: APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: fastapi-config
              key: APP_ENVIRONMENT
        - name: SECRET_API_KEY
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: SECRET_API_KEY

