apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        # IMPORTANT: Change this to your actual Docker Hub username!
        image: neyo55/fastapi-app:v1
        ports:
        - containerPort: 8000
