---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fastapi-secret
  namespace: default
spec:
  encryptedData:
    SECRET_API_KEY: AgC7ygaXeCV7MseMOM4Uf8rdqC6oImbWBGorGvbO2LPWwAEji03W1R4xYcPNgNXfyXtudzFpCdRdV14BKoaRzlWWP0YsbC3KqJn31ct122IWCusQHv354QsADdvB5bGRXp96/OxFaW2ESNEz8pY3dRjr+vLTUvHIBOzZIzAF1i4mDPIow5scxLS2n3fA2IBIEaUSyR7uLg8L6XkNsFQ+3xdtpoDqaR3eCO/8HC4Z94oJsqEcXzIHqnxXK+5+WVS35D7aZzyyC8sqyMYgCi6PPQ0obC2t8nRx4FzDMoMuvcUgOmiCuu3CRvhJ7aqwhmkhG4WKkdnKd+iUPlmXLhPSD5w8v+vUtRrJCbIPpVXlQ90vsuRYp2pPwTP/qHGD08ZTUZ2uEvG6ZKsn9PVGu2LAaPefYMwn1UDStGXmRC6sVTDYOv8mtbRfbJ5yEYiLGr+DXrdb1nsaGOMdbHIrm0153Mgx0jGKvOlcxLs62I4OEt9QNluUYXLTmX1NM44ApFoUR/GaIoJzGb5sRH7LqRpl8M28IsCVIENsehQ+beoDK9GlfJxCBU9nFQgUvF2d4zWLzu0YYzuxmb83kDuPAugWQLBUMqCfGRlCEhlg1sDqS8LEbjc1Se99gL5Lll0kgQ5N+xDwMYc9/58bqxgBEiZiXoGFMIKu/U4LcBBlU3lrv/FnMbGPYOZCPcIitai6PQXbqCTKTybaIewin9cOt8ZoWJvKg76s
  template:
    metadata:
      creationTimestamp: null
      name: fastapi-secret
      namespace: default
    type: Opaque
